-- CreateTable
CREATE TABLE "OpenCandelData" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "open_1" DOUBLE PRECISION NOT NULL,
    "open_2" DOUBLE PRECISION NOT NULL,
    "open_3" DOUBLE PRECISION NOT NULL,
    "open_4" DOUBLE PRECISION NOT NULL,
    "open_5" DOUBLE PRECISION NOT NULL,
    "open_6" DOUBLE PRECISION NOT NULL,
    "open_7" DOUBLE PRECISION NOT NULL,
    "open_8" DOUBLE PRECISION NOT NULL,
    "open_9" DOUBLE PRECISION NOT NULL,
    "open_10" DOUBLE PRECISION NOT NULL,
    "open_11" DOUBLE PRECISION NOT NULL,
    "open_12" DOUBLE PRECISION NOT NULL,
    "open_13" DOUBLE PRECISION NOT NULL,
    "open_14" DOUBLE PRECISION NOT NULL,
    "open_15" DOUBLE PRECISION NOT NULL,
    "open_16" DOUBLE PRECISION NOT NULL,
    "open_17" DOUBLE PRECISION NOT NULL,
    "open_18" DOUBLE PRECISION NOT NULL,
    "open_19" DOUBLE PRECISION NOT NULL,
    "open_20" DOUBLE PRECISION NOT NULL,
    "open_21" DOUBLE PRECISION NOT NULL,
    "open_22" DOUBLE PRECISION NOT NULL,
    "open_23" DOUBLE PRECISION NOT NULL,
    "open_24" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "OpenCandelData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CloseCandelData" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "close_1" DOUBLE PRECISION NOT NULL,
    "close_2" DOUBLE PRECISION NOT NULL,
    "close_3" DOUBLE PRECISION NOT NULL,
    "close_4" DOUBLE PRECISION NOT NULL,
    "close_5" DOUBLE PRECISION NOT NULL,
    "close_6" DOUBLE PRECISION NOT NULL,
    "close_7" DOUBLE PRECISION NOT NULL,
    "close_8" DOUBLE PRECISION NOT NULL,
    "close_9" DOUBLE PRECISION NOT NULL,
    "close_10" DOUBLE PRECISION NOT NULL,
    "close_11" DOUBLE PRECISION NOT NULL,
    "close_12" DOUBLE PRECISION NOT NULL,
    "close_13" DOUBLE PRECISION NOT NULL,
    "close_14" DOUBLE PRECISION NOT NULL,
    "close_15" DOUBLE PRECISION NOT NULL,
    "close_16" DOUBLE PRECISION NOT NULL,
    "close_17" DOUBLE PRECISION NOT NULL,
    "close_18" DOUBLE PRECISION NOT NULL,
    "close_19" DOUBLE PRECISION NOT NULL,
    "close_20" DOUBLE PRECISION NOT NULL,
    "close_21" DOUBLE PRECISION NOT NULL,
    "close_22" DOUBLE PRECISION NOT NULL,
    "close_23" DOUBLE PRECISION NOT NULL,
    "close_24" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "CloseCandelData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MaxCandelData" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "max_1" DOUBLE PRECISION NOT NULL,
    "max_2" DOUBLE PRECISION NOT NULL,
    "max_3" DOUBLE PRECISION NOT NULL,
    "max_4" DOUBLE PRECISION NOT NULL,
    "max_5" DOUBLE PRECISION NOT NULL,
    "max_6" DOUBLE PRECISION NOT NULL,
    "max_7" DOUBLE PRECISION NOT NULL,
    "max_8" DOUBLE PRECISION NOT NULL,
    "max_9" DOUBLE PRECISION NOT NULL,
    "max_10" DOUBLE PRECISION NOT NULL,
    "max_11" DOUBLE PRECISION NOT NULL,
    "max_12" DOUBLE PRECISION NOT NULL,
    "max_13" DOUBLE PRECISION NOT NULL,
    "max_14" DOUBLE PRECISION NOT NULL,
    "max_15" DOUBLE PRECISION NOT NULL,
    "max_16" DOUBLE PRECISION NOT NULL,
    "max_17" DOUBLE PRECISION NOT NULL,
    "max_18" DOUBLE PRECISION NOT NULL,
    "max_19" DOUBLE PRECISION NOT NULL,
    "max_20" DOUBLE PRECISION NOT NULL,
    "max_21" DOUBLE PRECISION NOT NULL,
    "max_22" DOUBLE PRECISION NOT NULL,
    "max_23" DOUBLE PRECISION NOT NULL,
    "max_24" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "MaxCandelData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MinCandelData" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "min_1" DOUBLE PRECISION NOT NULL,
    "min_2" DOUBLE PRECISION NOT NULL,
    "min_3" DOUBLE PRECISION NOT NULL,
    "min_4" DOUBLE PRECISION NOT NULL,
    "min_5" DOUBLE PRECISION NOT NULL,
    "min_6" DOUBLE PRECISION NOT NULL,
    "min_7" DOUBLE PRECISION NOT NULL,
    "min_8" DOUBLE PRECISION NOT NULL,
    "min_9" DOUBLE PRECISION NOT NULL,
    "min_10" DOUBLE PRECISION NOT NULL,
    "min_11" DOUBLE PRECISION NOT NULL,
    "min_12" DOUBLE PRECISION NOT NULL,
    "min_13" DOUBLE PRECISION NOT NULL,
    "min_14" DOUBLE PRECISION NOT NULL,
    "min_15" DOUBLE PRECISION NOT NULL,
    "min_16" DOUBLE PRECISION NOT NULL,
    "min_17" DOUBLE PRECISION NOT NULL,
    "min_18" DOUBLE PRECISION NOT NULL,
    "min_19" DOUBLE PRECISION NOT NULL,
    "min_20" DOUBLE PRECISION NOT NULL,
    "min_21" DOUBLE PRECISION NOT NULL,
    "min_22" DOUBLE PRECISION NOT NULL,
    "min_23" DOUBLE PRECISION NOT NULL,
    "min_24" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "MinCandelData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TimeCandelData" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "time_1" DOUBLE PRECISION NOT NULL,
    "time_2" DOUBLE PRECISION NOT NULL,
    "time_3" DOUBLE PRECISION NOT NULL,
    "time_4" DOUBLE PRECISION NOT NULL,
    "time_5" DOUBLE PRECISION NOT NULL,
    "time_6" DOUBLE PRECISION NOT NULL,
    "time_7" DOUBLE PRECISION NOT NULL,
    "time_8" DOUBLE PRECISION NOT NULL,
    "time_9" DOUBLE PRECISION NOT NULL,
    "time_10" DOUBLE PRECISION NOT NULL,
    "time_11" DOUBLE PRECISION NOT NULL,
    "time_12" DOUBLE PRECISION NOT NULL,
    "time_13" DOUBLE PRECISION NOT NULL,
    "time_14" DOUBLE PRECISION NOT NULL,
    "time_15" DOUBLE PRECISION NOT NULL,
    "time_16" DOUBLE PRECISION NOT NULL,
    "time_17" DOUBLE PRECISION NOT NULL,
    "time_18" DOUBLE PRECISION NOT NULL,
    "time_19" DOUBLE PRECISION NOT NULL,
    "time_20" DOUBLE PRECISION NOT NULL,
    "time_21" DOUBLE PRECISION NOT NULL,
    "time_22" DOUBLE PRECISION NOT NULL,
    "time_23" DOUBLE PRECISION NOT NULL,
    "time_24" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "TimeCandelData_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OpenCandelData_bot_code_tf_key" ON "OpenCandelData"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "CloseCandelData_bot_code_tf_key" ON "CloseCandelData"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "MaxCandelData_bot_code_tf_key" ON "MaxCandelData"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "MinCandelData_bot_code_tf_key" ON "MinCandelData"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "TimeCandelData_bot_code_tf_key" ON "TimeCandelData"("bot", "code", "tf");
