-- CreateTable
CREATE TABLE "CurrencyCandelsHistory" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "Time" DOUBLE PRECISION NOT NULL,
    "Open" DOUBLE PRECISION NOT NULL,
    "Close" DOUBLE PRECISION NOT NULL,
    "Max" DOUBLE PRECISION NOT NULL,
    "Min" DOUBLE PRECISION NOT NULL,
    "Volume" DOUBLE PRECISION NOT NULL,
    "Date" TEXT NOT NULL,
    "Attention" DOUBLE PRECISION NOT NULL,
    "Veryfication" DOUBLE PRECISION NOT NULL,
    "L11" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "L21" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "delta1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "date1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "L12" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "L22" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "delta2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "date2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "L3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "L4" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "CurrencyCandelsHistory_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CurrencyCandelsHistory_bot_code_tf_key" ON "CurrencyCandelsHistory"("bot", "code", "tf");
