-- CreateTable
CREATE TABLE "ETF2MonthEquity" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "month_24" DOUBLE PRECISION NOT NULL,
    "month_23" DOUBLE PRECISION NOT NULL,
    "month_22" DOUBLE PRECISION NOT NULL,
    "month_21" DOUBLE PRECISION NOT NULL,
    "month_20" DOUBLE PRECISION NOT NULL,
    "month_19" DOUBLE PRECISION NOT NULL,
    "month_18" DOUBLE PRECISION NOT NULL,
    "month_17" DOUBLE PRECISION NOT NULL,
    "month_16" DOUBLE PRECISION NOT NULL,
    "month_15" DOUBLE PRECISION NOT NULL,
    "month_14" DOUBLE PRECISION NOT NULL,
    "month_13" DOUBLE PRECISION NOT NULL,
    "month_12" DOUBLE PRECISION NOT NULL,
    "month_11" DOUBLE PRECISION NOT NULL,
    "month_10" DOUBLE PRECISION NOT NULL,
    "month_9" DOUBLE PRECISION NOT NULL,
    "month_8" DOUBLE PRECISION NOT NULL,
    "month_7" DOUBLE PRECISION NOT NULL,
    "month_6" DOUBLE PRECISION NOT NULL,
    "month_5" DOUBLE PRECISION NOT NULL,
    "month_4" DOUBLE PRECISION NOT NULL,
    "month_3" DOUBLE PRECISION NOT NULL,
    "month_2" DOUBLE PRECISION NOT NULL,
    "month_1" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ETF2MonthEquity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ETF3MonthEquity" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "month_24" DOUBLE PRECISION NOT NULL,
    "month_23" DOUBLE PRECISION NOT NULL,
    "month_22" DOUBLE PRECISION NOT NULL,
    "month_21" DOUBLE PRECISION NOT NULL,
    "month_20" DOUBLE PRECISION NOT NULL,
    "month_19" DOUBLE PRECISION NOT NULL,
    "month_18" DOUBLE PRECISION NOT NULL,
    "month_17" DOUBLE PRECISION NOT NULL,
    "month_16" DOUBLE PRECISION NOT NULL,
    "month_15" DOUBLE PRECISION NOT NULL,
    "month_14" DOUBLE PRECISION NOT NULL,
    "month_13" DOUBLE PRECISION NOT NULL,
    "month_12" DOUBLE PRECISION NOT NULL,
    "month_11" DOUBLE PRECISION NOT NULL,
    "month_10" DOUBLE PRECISION NOT NULL,
    "month_9" DOUBLE PRECISION NOT NULL,
    "month_8" DOUBLE PRECISION NOT NULL,
    "month_7" DOUBLE PRECISION NOT NULL,
    "month_6" DOUBLE PRECISION NOT NULL,
    "month_5" DOUBLE PRECISION NOT NULL,
    "month_4" DOUBLE PRECISION NOT NULL,
    "month_3" DOUBLE PRECISION NOT NULL,
    "month_2" DOUBLE PRECISION NOT NULL,
    "month_1" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ETF3MonthEquity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ETF1MonthPriceChange" (
    "id" SERIAL NOT NULL,
    "bot" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
    "oneMonth_1" DOUBLE PRECISION NOT NULL,
    "oneMonth_2" DOUBLE PRECISION NOT NULL,
    "oneMonth_3" DOUBLE PRECISION NOT NULL,
    "oneMonth_4" DOUBLE PRECISION NOT NULL,
    "oneMonth_5" DOUBLE PRECISION NOT NULL,
    "oneMonth_6" DOUBLE PRECISION NOT NULL,
    "oneMonth_7" DOUBLE PRECISION NOT NULL,
    "oneMonth_8" DOUBLE PRECISION NOT NULL,
    "oneMonth_9" DOUBLE PRECISION NOT NULL,
    "oneMonth_10" DOUBLE PRECISION NOT NULL,
    "threeMonth_1" DOUBLE PRECISION NOT NULL,
    "threeMonth_2" DOUBLE PRECISION NOT NULL,
    "threeMonth_3" DOUBLE PRECISION NOT NULL,
    "threeMonth_4" DOUBLE PRECISION NOT NULL,
    "threeMonth_5" DOUBLE PRECISION NOT NULL,
    "threeMonth_6" DOUBLE PRECISION NOT NULL,
    "threeMonth_7" DOUBLE PRECISION NOT NULL,
    "threeMonth_8" DOUBLE PRECISION NOT NULL,
    "threeMonth_9" DOUBLE PRECISION NOT NULL,
    "threeMonth_10" DOUBLE PRECISION NOT NULL,
    "minSpread" DOUBLE PRECISION NOT NULL,
    "maxSpread" DOUBLE PRECISION NOT NULL,
    "fastMomentum" DOUBLE PRECISION NOT NULL,
    "slowMomentum" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ETF1MonthPriceChange_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ETF2MonthEquity_bot_code_tf_key" ON "ETF2MonthEquity"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "ETF3MonthEquity_bot_code_tf_key" ON "ETF3MonthEquity"("bot", "code", "tf");

-- CreateIndex
CREATE UNIQUE INDEX "ETF1MonthPriceChange_bot_code_tf_key" ON "ETF1MonthPriceChange"("bot", "code", "tf");
