-- AlterTable
ALTER TABLE "textsETF1" ADD COLUMN     "bot" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
ADD COLUMN     "code" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h',
ADD COLUMN     "tf" "ETFCRYPTO1Tf" NOT NULL DEFAULT 'h';
