-- AlterTable
ALTER TABLE "VirtualWallet" ADD COLUMN     "checkDatePie" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "datePie" TEXT NOT NULL DEFAULT '1',
ADD COLUMN     "missedTokensPie" DOUBLE PRECISION NOT NULL DEFAULT 0;
