-- CreateTable
CREATE TABLE "UserProfit" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL DEFAULT 'test@gmail.com',
    "etf_1" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "etf_2" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "etf_3" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "lots" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserProfit_pkey" PRIMARY KEY ("id")
);
