-- CreateTable
CREATE TABLE "OrdersHistory" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL DEFAULT 'test@gmail.com',
    "typeOfETF" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "bidPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "askPrice" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "bidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "askAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "averageValue" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT '',
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "type" TEXT NOT NULL DEFAULT '',
    "executPrecent" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "initialAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "OrdersHistory_pkey" PRIMARY KEY ("id")
);
